Added maintainer scripts
prometheus/jmx_exporter pull request #855
Opened 2023-07-26 02:46 UTC by dhoard

Added maintainer scripts to allow for easier releases/release testing.

2023-07-28 13:05 UTC, fstab requested changes
I'm wondering if we could use the Maven spottless plugin for checking the license header and running the Google Java code formatter. Then we would not need to check in a JAR file in Git, and we could include it in the standard Maven build rather than calling shell scripts.

https://github.com/diffplug/spotless/tree/main/plugin-maven

2023-07-29 15:59 UTC, dhoard commented on tools/build-and-copy.sh
> +fi
Removed

2023-07-29 15:59 UTC, dhoard commented on tools/build-and-copy.sh
> +git commit -m "${VERSION}"
Good catch. Added command to reset the branch.

2023-07-29 16:00 UTC, dhoard commented on tools/build-and-copy.sh
> +function check_exit_code () {
I decided to use a function so that I could pass a message. `set -e` will make the script fail, but makes debugging harder.

2023-08-11 14:02 UTC, dhoard commented
Closing. Will open a new PR with just the scripts.

2023-08-11 14:02 UTC, closed without merging